#!/usr/bin/env bash
set -euo pipefail

# Points this crate's cargo target-dir at local (non-CIFS) disk by generating
# emulator/.cargo/config.toml. Required because /mnt/fileserver is a CIFS mount
# (cache=strict,actimeo=1) where exec'ing a binary shortly after cargo writes
# it can transiently fail with EINVAL ("Invalid argument (os error 22)") — see
# QUICKSTART.md's Troubleshooting section (bd: mc-e70, mc-73k).
#
# Cargo config.toml does not expand `~` or `${VAR}` in path values (verified
# against cargo 1.96.1), so a single committed config can't hold a path that's
# correct for every user/host. This script resolves the real path at run time
# and writes it to a git-ignored file instead. Safe to re-run.
#
# The target-dir is keyed by the crate's own absolute path so that each git
# worktree (this repo keeps several under worktrees/) gets its own target-dir
# instead of contending for one shared lock/build cache.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CRATE_DIR="$(dirname "$SCRIPT_DIR")"

CHECKOUT_KEY="$(printf '%s' "$CRATE_DIR" | md5sum | cut -c1-10)"
TARGET_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/pc6502-emulator/cargo-target-$CHECKOUT_KEY"
mkdir -p "$TARGET_DIR"

CONFIG_DIR="$CRATE_DIR/.cargo"
CONFIG_FILE="$CONFIG_DIR/config.toml"
mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" <<EOF
# Generated by scripts/ensure-local-cargo-target.sh — local to this user/host,
# not committed (see .gitignore). Re-run the script if this file is missing
# or points at a stale/invalid path.
[build]
target-dir = "$TARGET_DIR"
EOF

echo "crate:                    $CRATE_DIR"
echo "cargo target-dir set to: $TARGET_DIR"
echo "config written to:       $CONFIG_FILE"
